# Setup
title: Alessandro Melandri
tagline: IT Project Manager, strimpello la chitarra, fotografo particolari insignificanti, studio la Lingua dei Segni Italiana. Follow me on <a href="https://mastodon.uno/@alemelandri"><i class="fa-brands fa-mastodon"></i> Mastodon</a> or <a href="https://www.linkedin.com/in/alessandromelandri/"><i class="fa-brands fa-linkedin"></i> Linkedin</a>
url: https://getpoole.com
paginate: 10
baseurl: ""
permalink: :title
excerpt_separator: <!--more-->

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Alessandro Melandri
  url: https://melandri.net
  email: 

# Custom vars
version: 3.0.0
