name: Alessandro Melandri
author: Alessandro Melandri
url: http://melandri.net
staticurl: http://melandri.net/static/

title: Alessandro Melandri

# ------------------------------------------
# General settings

destination: _site

highliter: true
exclude: [readme.md]
encoding: UTF-8

# ------------------------------------------
# Post settings

permalink: :title/

plugins: [jekyll-sitemap]
